### ISSUE TITLE
2.0.0-preview2 version doesn't seem to work with Microsoft.Azure.Documents.Client.TransientFaultHandling when used in SSIS script task

### ISSUE THREAD

**Issue by pramod-hegde** [Azure/azure-cosmosdb-dotnet#574]
Always get this error in SSIS script task (C#)

```
Error: System.MissingMethodException: Method not found: 'Microsoft.Azure.Documents.Client.TransientFaultHandling.IReliableReadWriteDocumentClient Microsoft.Azure.Documents.Client.TransientFaultHandling.DocumentClientExtensions.AsReliable(Microsoft.Azure.Documents.Client.DocumentClient, Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.RetryStrategy)'.
   at ScriptMain.CreateReliableClient(DocumentClient c)
   at ScriptMain.CreateDocClient()
   at ScriptMain.PreExecute()
```

I have a SSIS package and I created a script task. Initially, when I used DocumentClient 1.11.0.0 version along with Documents.Client.TransientFaultHandling 1.5.0.0, it worked without any such issues. But 1.11.0.0 had some issues for which DocDb Engg Team suggested that I should upgrade to the latest version. So, when I upgraded the version to 2.0.0.0 preview, I'm unable to run the script task.

here is my code snippet,

```
IReliableReadWriteDocumentClient client = null;

public override void PreExecute ()
{

DocumentClient c =new DocumentClient(new Uri(Variables.CosmosDbEndpoint), Variables.CosmosDbAccountKey, DefaulConnectionPolicy, desiredConsistencyLevel: ConsistencyLevel.Eventual);

client = c.AsReliable(DefaulDocumentDbRetryStrategy);   //**its failing here**

client.OpenAsync();

}

private DocumentDbRetryStrategy DefaulDocumentDbRetryStrategy
    {
        get
        {
            return new DocumentDbRetryStrategy(RetryStrategy.DefaultExponential)
            {
                FastFirstRetry = true
            };
        }
    }

    private ConnectionPolicy DefaulConnectionPolicy
    {
        get
        {
            return new ConnectionPolicy
            {
                ConnectionMode = ConnectionMode.Direct,
                ConnectionProtocol = Protocol.Tcp,
                RetryOptions = new RetryOptions
                {
                    MaxRetryAttemptsOnThrottledRequests = 30,
                    MaxRetryWaitTimeInSeconds = 10
                }
            };
        }
    }

```

I initially thought that having multiple versions of DocumentClient (1.11.0.0 & 2.0.0.0) would have caused this issue. Then I removed v1.11.0.0 from GAC. After that I got the following error,

```
Error: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at ScriptMain.CreateReliableClient(DocumentClient c)
   at ScriptMain.CreateDocClient()
   at ScriptMain.PreExecute()

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\<user>\AppData\Local\Microsoft\Microsoft SQL Server\140\SSIS\130\x86\DtsDebugHost.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/<user>/AppData/Local/Microsoft/Microsoft SQL Server/140/SSIS/130/x86/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.Azure.Documents.Client.TransientFaultHandling, Version=1.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\<user>\AppData\Local\Microsoft\Microsoft SQL Server\140\SSIS\130\x86\DtsDebugHost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Users/<user>/AppData/Local/Microsoft/Microsoft SQL Server/140/SSIS/130/x86/Microsoft.Azure.Documents.Client.DLL.
LOG: Attempting download of new URL file:///C:/Users/<user>/AppData/Local/Microsoft/Microsoft SQL Server/140/SSIS/130/x86/Microsoft.Azure.Documents.Client/Microsoft.Azure.Documents.Client.DLL.
LOG: Attempting download of new URL file:///C:/Users/<user>/AppData/Local/Microsoft/Microsoft SQL Server/140/SSIS/130/x86/Microsoft.Azure.Documents.Client.EXE.
LOG: Attempting download of new URL file:///C:/Users/<user>/AppData/Local/Microsoft/Microsoft SQL Server/140/SSIS/130/x86/Microsoft.Azure.Documents.Client/Microsoft.Azure.Documents.Client.EXE.
```

Looks like TransientFaultHandling library has a hard dependency on the DocumentClientVersion 1.11.0.0

![image](https://user-images.githubusercontent.com/20237168/44187466-2eca8700-a13a-11e8-94cc-351e47b2cea5.png)

If this the issue, can you please fix this issue at the earliest?

**Comment by ealsur** [comment]
The TransientFaultHandling package was for a time (2016) when the Cosmos DB SDK did not have a retrying logic in place. Since version 1.8, [Automatic retries are supported](https://azure.microsoft.com/en-us/updates/documentdb-sdk-support-for-automatic-retries-parallel-query-execution-and-performance-improvements/).

You shouldn't need the TransientFaultHandling package anymore.

**Comment by ealsur** [comment]
Closing, please reopen in case you have any other questions.
