### ISSUE TITLE
MissingMethodException using ChangefeedProcessor on top of docdb sdk 2.0

### ISSUE THREAD

**Issue by eiriktsarpalis** [Azure/azure-cosmosdb-dotnet#578]
Attempting to use the ChangefeedProcessor library on top of  CosmosDB SDK 2.0 results in the following runtime error:
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Client.ResourceResponse`1<Microsoft.Azure.Documents.Document>> Microsoft.Azure.Documents.Client.DocumentClient.ReadDocumentAsync(System.Uri, Microsoft.Azure.Documents.Client.RequestOptions)'.
   at Microsoft.Azure.Documents.ChangeFeedProcessor.DataAccess.ChangeFeedDocumentClient.ReadDocumentAsync(Uri documentUri)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Documents.ChangeFeedProcessor.DataAccess.ChangeFeedDocumentClient.ReadDocumentAsync(Uri documentUri)
   at Microsoft.Azure.Documents.ChangeFeedProcessor.Utils.DocumentClientExtensions.TryGetDocumentAsync(IChangeFeedDocumentClient client, Uri documentUri)
   at Microsoft.Azure.Documents.ChangeFeedProcessor.Bootstrapping.LeaseStore.IsInitializedAsync()
   at Microsoft.Azure.Documents.ChangeFeedProcessor.Bootstrapping.Bootstrapper.InitializeAsync()
   at Microsoft.Azure.Documents.ChangeFeedProcessor.PartitionManagement.PartitionManager.StartAsync()
   at Microsoft.Azure.Documents.ChangeFeedProcessor.ChangeFeedProcessor.StartAsync()
```
Seems to be cause by a break in the CosmosDB SDK ABI. This issue blocks our ability to run changefeed on Linux (due to issue #194). This problem can be easily fixed by releasing a build of the changefeed library that targets version 2.0 of the SDK.

**Comment by ealsur** [comment]
@eiriktsarpalis What version of the Change Feed Processor library are you using?

**Comment by eiriktsarpalis** [comment]
ChangeFeed version 2.0.6 and Core SDK version 2.0.0-preview2

**Comment by ealsur** [comment]
@eiriktsarpalis I created an issue in the CFP Library repo to track and a PR to address it: https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet/pull/97

**Comment by eiriktsarpalis** [comment]
Thanks, I wasn't aware of that repo.
