### ISSUE TITLE
GraphBulkExecutor.InitializeAsync breaks creating new DocumentClients

### ISSUE THREAD

**Issue by AArnott** [Azure/azure-cosmosdb-dotnet#617]
**Describe the bug**

After calling `graphBulkImporter.InitializeAsync`, future attempts to create `DocumentClient` constructors throw `System.FormatException` with the message:

> The format of value '.NET/BulkExecutorLibrary/' is invalid.

**To Reproduce**

```cs
        var docClient = new DocumentClient(new Uri($"https://{accountName}.documents.azure.com/"), cloudStorageKey);
        Database database = await docClient.CreateDatabaseIfNotExistsAsync(new Database { Id = databaseId });
        var graph = await docClient.CreateDocumentCollectionIfNotExistsAsync(
            UriFactory.CreateDatabaseUri(databaseId),
            new DocumentCollection
            {
                Id = "somegraph",
            });
        var graphBulkImporter = new GraphBulkExecutor(docClient, graph);

        await graphBulkImporter.InitializeAsync(); // REMOVE this line to eliminate the repro

        docClient.Dispose();

        docClient = new DocumentClient(new Uri($"https://{accountName}.documents.azure.com/"), cloudStorageKey);
```

**Expected behavior**

I expect that running `GraphBulkImporter.InitializeAsync` makes no changes to static state that would break creating future objects (that may even be completely unrelated to the `GraphBulkImporter`).

**Actual behavior**

I can only create `DocumentClient` objects until the first initialization of `GraphBulkImporter`. After that, creating these objects is broken for the life of the `AppDomain`. This breaks unit tests that include bulk uploading, as well as applications that use the bulk importer.

**Environment summary**
SDK Version: Microsoft.Azure.CosmosDB.BulkExecutor 1.0.2

**Additional context**
```
Result StackTrace:	
at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)
   at Microsoft.Azure.Documents.HttpClientExtension.AddUserAgentHeader(HttpClient httpClient, UserAgentContainer userAgent)
   at Microsoft.Azure.Documents.Client.DocumentClient.Initialize(Uri serviceEndpoint, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel)
   at Microsoft.Azure.Documents.Client.DocumentClient..ctor(Uri serviceEndpoint, String authKeyOrResourceToken, EventHandler`1 sendingRequestEventArgs, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel)
   at Microsoft.Azure.Documents.Client.DocumentClient..ctor(Uri serviceEndpoint, String authKeyOrResourceToken, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel)
   at GremlinExportTests.<Foo1>d__7.MoveNext() in D:\git\Tests\GremlinExportTests.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	System.FormatException : The format of value '.NET/BulkExecutorLibrary/' is invalid.
```

**Comment by AArnott** [comment]
This repros with Microsoft.Azure.CosmosDB.BulkExecutor 1.1.1 as well.

**Comment by tknandu** [comment]
@AArnott - Can you please share the rest of the code after you dispose the DocumentClient and recreate a new one. The BulkExecutor instance would be holding a reference to the disposed client - so I want to know what you attempt to do after what you shared in the code snippet

**Comment by AArnott** [comment]
This is the entire code snippet. The last line is the one to throw the exception.

**Comment by AArnott** [comment]
We need a fix or a workaround to this ASAP. We are running a single unit test at a time because any more than that hits this bug. This is an unacceptable way for us to check in our feature work.
