### ISSUE TITLE
GremlinDocumentQuery not threadsafe?

### ISSUE THREAD

**Issue by ChiefWiggum** [Azure/azure-cosmosdb-dotnet#622]
We run an aspnetcore 2.1 api that queries a cosmosdb graph. When the load gets bigger, we are experiencing the following exceptions:

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.ReflectionCache.GetParametersCached(MethodBase method)
   at Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.BuildCompatibleArgumentProjection(MethodBase m, Expression[] exprArgs, List`1& projectedArgs)
   at Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.FindBestMethod(Expression instanceExpression, IEnumerable`1 methods, Type[] typeArgs, Expression[] args, MethodProjection& methodProjection)
   at Microsoft.Azure.Graphs.GremlinGroovy.Binding.MemberBindHelper.FindMethod(Expression instanceExpression, Type type, String methodName, Type[] typeArgs, Expression[] args, BindingFlags flags)
   at Microsoft.Azure.Graphs.GremlinGroovy.GremlinGroovyTraversalScriptEngine.<>c__DisplayClass6_0.<CreateTraversalScript>b__0(ParameterExpression p)
   at Microsoft.Azure.Graphs.GremlinGroovy.ParameterBinding.Create(GroovyVariable groovyVariable, ParameterExpression parameterExpression, Func`2 bindingExpressionFunc)
   at Microsoft.Azure.Graphs.GremlinGroovy.GremlinGroovyTraversalScriptEngine.CreateBinding(String variableName, String groovyClassName, ParameterExpression parameter, Func`2 bindingFunc)
   at Microsoft.Azure.Graphs.GremlinGroovy.GremlinGroovyTraversalScriptEngine.CreateTraversalScript(String gremlinScript)
   at Microsoft.Azure.Graphs.GraphCommand.<ExecuteTraversalAsync>b__42_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Graphs.GraphCommand.ExecuteTraversalAsync()
   at Microsoft.Azure.Graphs.GremlinDocumentQuery`1.InitializeGraphTraversalAync()
   at Microsoft.Azure.Graphs.GremlinDocumentQuery`1.ExecuteNextAsync[TResult](CancellationToken token)
   at [hidden].Data.Providers.CosmosDbProvider.GetRelatedVerticesOut(String idFrom, String relatedVertexLabel, String edgeLabel, CosmosCollection collection)
   at [hidden].Controllers.ProfilesController.ProfileMaterialized(ObjectEvent`1 evt) in [hidden]\Controllers\ProfilesController.cs:line 60
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Probably related: [ExecuteNextAsync() is not threadsafe over multiple GremlinDocumentQuery instances](https://github.com/Azure/azure-docs-sdk-dotnet/issues/804)

**Environment summary**
SDK Version: Microsoft.Azure.DocumentDB.Core, Version=1.9.1.0
OS Version: Windows 10

**Comment by BenjaBobs** [comment]
If at all feasible, I suggest trying [this](https://github.com/evo-terren/Gremlin.Net.CosmosDb) instead, as Microsoft.Azure.Graphs is not being developed anymore as far as I know.

**Comment by ChiefWiggum** [comment]
I found the following statement [here](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/31761100-open-source-microsoft-azure-graphs):

> Microsoft.Azure.Graphs is now deprecated. Use Gremlin.Net.

And will therefore removal all dependancies from the library and move to Gremlin.net.
Closing this issue.
